
[tool.check-manifest]
ignore = [".travis.yml",
          "docs/_function_autosummary/*"]

[tool.commitizen]
name = "cz_conventional_commits"
version = "101.6.3"
tag_format = "v$version"
version_files = ["VERSION"]
update_changelog_on_bump = true
